# Generated by Django 5.1.3 on 2024-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityid', models.CharField(db_column='activityID', max_length=10, primary_key=True, serialize=False)),
                ('activitytype', models.CharField(db_column='activityType', max_length=7)),
            ],
            options={
                'db_table': 'Activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('logid', models.AutoField(db_column='logID', primary_key=True, serialize=False)),
                ('actiontype', models.CharField(db_column='actionType', max_length=6)),
                ('tablename', models.CharField(db_column='tableName', max_length=50)),
                ('recordid', models.CharField(db_column='recordID', max_length=50)),
                ('actiondate', models.DateTimeField(db_column='actionDate')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AuditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetid', models.CharField(db_column='budgetID', max_length=15, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('budgetamount', models.DecimalField(blank=True, db_column='budgetAmount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('year', models.TextField(blank=True, null=True)),
                ('quarternumber', models.CharField(blank=True, db_column='quarterNumber', max_length=45, null=True)),
                ('quartername', models.CharField(blank=True, db_column='quarterName', max_length=45, null=True)),
                ('monthnumber', models.IntegerField(blank=True, db_column='monthNumber', null=True)),
                ('monthname', models.CharField(blank=True, db_column='monthName', max_length=45, null=True)),
                ('weeknumber', models.IntegerField(blank=True, db_column='weekNumber', null=True)),
                ('daynumber', models.IntegerField(blank=True, db_column='dayNumber', null=True)),
                ('dayname', models.CharField(blank=True, db_column='dayName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseid', models.CharField(db_column='expenseID', max_length=10, primary_key=True, serialize=False)),
                ('payeedetail', models.CharField(blank=True, db_column='payeeDetail', max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Expense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('incomeid', models.CharField(db_column='incomeID', max_length=10, primary_key=True, serialize=False)),
                ('payerdetail', models.CharField(db_column='payerDetail', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sourceid', models.CharField(db_column='sourceID', max_length=10, primary_key=True, serialize=False)),
                ('sourcename', models.CharField(db_column='sourceName', max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('userid', models.CharField(db_column='userID', max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=100)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'UserProfile',
                'managed': False,
            },
        ),
    ]
